modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = "TODO"
license = "LGPL-3.0"

[[mods]]
modId = "notenoughupdates"
version = "${version}"
displayName = "Not Enough Updates"
authors = "nea89"
description = '''
Not Enough Updates - A mod for Hypixel Skyblock
'''
#logoFile = ""

[[dependencies.notenoughupdates]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.notenoughupdates]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.notenoughupdates]]
modId = "architectury"
mandatory = true
versionRange = "[4.2.50,)"
ordering = "AFTER"
side = "BOTH"
