# SPDX-FileCopyrightText: 2023 Linnea Gräf <nea@nea.moe>
#
# SPDX-License-Identifier: CC0-1.0

repos:
    -   repo: https://github.com/fsfe/reuse-tool
        rev: v4.0.3
        hooks:
            -   id: reuse
    -   repo: local
        hooks:
            -   id: ordered_translations
                name: "Check translation ordering"
                language: script
                files: translations/.*
                entry: ./check-translation-ordering.sh
