project_id: "588173"
base_path: "."
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: false
base_url: "https://api.crowdin.com"
commit_message: "New translations"
append_commit_message: false
files:
    - source: "/src/main/resources/assets/firmament/lang/en_us.json"
      translation: "/src/main/resources/assets/firmament/lang/%locale_with_underscore%.json"

