name: Build
on:
    - push
    - pull_request

jobs:
    build:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              name: Checkout repository
            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  distribution: temurin
                  java-version: 17
            - name: Set up gradle cache
              uses: gradle/gradle-build-action@v2
            - name: Build with gradle
              run: ./gradlew clean test remapJar --stacktrace
            - name: Upload build artifact
              uses: actions/upload-artifact@v3
              with:
                  path: build/libs/Firmament-*.jar

