# SPDX-FileCopyrightText: 2023 Linnea Gräf <nea@nea.moe>
#
# SPDX-License-Identifier: CC0-1.0

name: Build
on:
    - push
    - pull_request

jobs:
    build:
        name: Test
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
                name: Checkout repository
                with:
                    fetch-tags: true
                    fetch-depth: 0
            -   name: Set up JDK 21
                uses: actions/setup-java@v4
                with:
                    distribution: temurin
                    java-version: 21
            -   name: Set up gradle cache
                uses: gradle/actions/setup-gradle@v3
            -   name: Build with gradle
                run: ./gradlew clean test remapJar --stacktrace
            -   name: Upload build artifact
                uses: actions/upload-artifact@v3
                with:
                    path: build/libs/Firmament-*.jar
            -   name: Move build artifact around and print check sum
                run: |
                    rm -f build/libs/*sources*.jar
                    sha256sum build/libs/*.jar
            -   name: Upload to discord
                run: |
                    curl "$WEBHOOK_URL" -X POST -H "Content-type: multipart/form-data" --form "files[0]=@$(echo build/libs/*.jar)"
                env:
                    WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
