# SPDX-FileCopyrightText: 2023 Linnea Gräf <nea@nea.moe>
#
# SPDX-License-Identifier: CC0-1.0

on:
    release:
        types:
            - published

jobs:
    upload-to-modrinth:
        runs-on: ubuntu-latest
        steps:
            -   run: |
                    gh release download "$TAG" -p '*.jar' --repo "$REPO"
                env:
                    TAG: ${{ github.event.release.tag_name }}
                    REPO: ${{ github.repository }}
                    GH_TOKEN: ${{ github.token }}
            -   run: |
                    printf %s "$CHANGELOG" > CHANGELOG.md
                env:
                    CHANGELOG: ${{ github.event.release.body }}
            -   uses: Kir-Antipov/mc-publish@v3.3
                with:
                    modrinth-id: IJNUBZ2a
                    modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
                    files: "*.jar"
                    loaders: fabric
                    version: ${{ github.event.release.tag_name }}
